config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'achievements#index'
  resources :users, only: %i[show edit] do
    resources :bookmarks, only: %i[create show update destroy]
  end
  resources :achievements, only: %i[index show new create]
  resources :tags, only: %i[index show]
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get 'images/ogp.png', to: 'images#ogp', as: 'images_ogp'
  get 'search', to: 'achievements#search'
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :achievement
  validates :achievement_id, uniqueness: { scope: [:user_id] }
  validates :user_id, presence: true
  validates :achievement_id, presence: true

  enum status: { locked: 0, unlocked: 1 }

  def reverse
    locked? ? unlocked! : locked!
    self
  end

  def unlock_date
    self[:unlock_date] if unlocked?
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :login_required, except: :show
  before_action :correct_user, except: :show

  def create
    @bookmark = Bookmark.new(user_id: current_user.id,
                             achievement_id: bookmark_params[:achievement_id],
                             status: :locked)
    if @bookmark.save
      render
    else
      redirect_to root_path
    end
  end

  def show
    @user = User.find(params[:user_id])
    @bookmark = @user.bookmarks.find(params[:id])
    redirect_to root_path if @bookmark.locked?
  end

  def update
    @bookmark = current_user.bookmarks.find(params[:id])
    @bookmark.reverse
    @bookmark.unlock_date = unlock_date if @bookmark.unlocked?
    @bookmark.save
  end

  def destroy
    @bookmark = current_user.bookmarks.find(params[:id])
    @bookmark.destroy
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:achievement_id, :unlock_date)
  end

  def correct_user
    user = User.find(params[:user_id])
    redirect_to root_path unless user == current_user
  end

  def unlock_date
    bookmark_params[:unlock_date].present? ? bookmark_params[:unlock_date] : Time.zone.now.to_date
  end
end

app/views/bookmarks/_unlocked_modal_body.html.erb
<div class="row">
  <h5 class="center-align">実績を解除しました！</h5>
  <div class="center-align">
  <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button"
     data-text="実績を解除しました! #リアル実績解除 #Unlock"
     data-url="<%= user_bookmark_url(current_user, bookmark) %>"
     data-lang="ja"
     target="_blank"
     rel="noopener noreferrer">Tweet</a>
  <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  </div>
  <div id="unlock-sign"></div>
</div>
<div class="row">
  <div class="col-12">
    <%= image_tag(images_ogp_path(params: { text: bookmark.achievement.title }), class: "responsive-img") %>
  </div>
</div>

app/views/bookmarks/_unlocked_modal_footer.html.erb
<button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="window.location.reload();">戻る</button>

app/views/bookmarks/create.js.erb
$("#achievement-card-<%= @bookmark.achievement.id %>").html('<%= j(render "achievements/achievement_card", { achievement: @bookmark.achievement }) %>')
$("#card-action-<%= @bookmark.achievement.id %>").html('<%= j(render "users/card_action", { bookmark: @bookmark }) %>')

app/views/bookmarks/destroy.js.erb
$("#bookmark-edit-card-<%= @bookmark.id %>").remove()

app/views/bookmarks/show.html.erb
<% set_meta_tags description: "#{@user.nickname}さんが実績を解除しました！",
                 og: {
                   title: :description,
                   description: :description,
                   url: user_bookmark_url(@user, @bookmark),
                   image: images_ogp_url(params: { text: @bookmark.achievement.title })
                 } %>
<br>
<%= image_tag(images_ogp_path(params: { text: @bookmark.achievement.title }), class: "responsive-img") %>
<br>
<br>
<div class="row">
  <div class="col-12">
    <h4><%= "#{@user.nickname} さんが" unless @user == current_user %> 実績を解除しました！</h4>
    <% if @user == current_user %>
      <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button"
         data-text="実績を解除しました! #リアル実績解除 #Unlock"
         data-url="<%= user_bookmark_url(current_user, @bookmark) %>"
         data-lang="ja"
         target="_blank"
         rel="noopener noreferrer">Tweet</a>
      <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    <% end %>
  </div>
</div>
<div class="row">
  <% if current_user %>
    <% if @user == current_user %>
      <div class="col s12 l6">
        <%= link_to 'みんなの実績を見る', achievements_path, class: "btn btn-block" %>
      </div>
      <div class="col s12 col l6">
          <%= link_to '自分の実績を見る', user_path(current_user), class: "btn light-blue accent-3 btn-block" %>
      </div>
    <% else %>
      <div class="col s12 l3">
        <%= link_to "#{@user.nickname} さんの実績を見る", user_path(@user), class: "btn red btn-block" %>
      </div>
      <div class="col s12 l3">
        <%= link_to 'みんなの実績を見る', achievements_path, class: "btn btn-block" %>
      </div>
      <div class="col s12 l3">
        <%= link_to '自分の実績を見る', user_path(current_user), class: "btn light-blue accent-3 btn-block" %>
      </div>
      <div class="col s12 l3">
        <% if @bookmark.achievement.users.include?(current_user) %>
          <a class="btn disabled btn-block">ストック済</a>
        <% else %>
          <%= link_to 'この実績をストックする', user_bookmarks_path(current_user, params: { bookmark: { achievement_id: @bookmark.achievement.id } }), method: :post, class: "btn orange btn-block" %>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="col s12 l4">
      <%= link_to "#{@user.nickname} さんの実績を見る", user_path(@user), class: "btn red btn-block" %>
    </div>
    <div class="col s12 l4">
      <%= link_to 'みんなの実績を見る', achievements_path, class: "btn btn-block" %>
    </div>
    <div class="col s12 l4">
        <%= link_to 'ログインする', '/auth/twitter', class: "btn light-blue accent-3 btn-block" %>
    </div>
  <% end %>
</div>

app/views/bookmarks/update.js.erb
<% if @bookmark.unlocked? %>
  $("#modal-body-<%= @bookmark.id %>").html('<%= j(render "unlocked_modal_body", { bookmark: @bookmark }) %>')
  $("#modal-footer-<%= @bookmark.id %>").remove()
<% else %>
  $("#bookmark-edit-card-<%= @bookmark.id %>").remove()
  $("#edit-locked-bookmarks").append('<%= j(render "users/bookmark_edit_card", { bookmark: @bookmark }) %>')
<% end %>