config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'achievements#index'
  resources :users, only: %i[show edit] do
    resources :bookmarks, only: %i[create show update destroy]
  end
  resources :achievements, only: %i[index show new create]
  resources :tags, only: %i[index show]
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get 'images/ogp.png', to: 'images#ogp', as: 'images_ogp'
  get 'search', to: 'achievements#search'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookmarks
  has_many :achievements, through: :bookmarks

  def self.find_or_create_from_auth_hash(auth_hash)
    attributes = { provider: auth_hash[:provider],
                   uid: auth_hash[:uid],
                   nickname: auth_hash[:info][:name],
                   image_url: auth_hash[:extra][:raw_info][:profile_image_url_https] }
    user = User.find_or_create_by(provider: attributes[:provider], uid: attributes[:uid])
    user.update_attributes(attributes) && user
  end

  def unlocked_bookmarks
    bookmarks.unlocked
  end

  def locked_bookmarks
    bookmarks.locked
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit]

  def show
    @user = User.includes(:bookmarks).find(params[:id])
    @unlocked_bookmarks = @user.unlocked_bookmarks.order(unlock_date: 'DESC').page(params[:unlocked_page]).per(10)
    @locked_bookmarks = @user.locked_bookmarks.order(created_at: 'DESC').page(params[:locked_page]).per(10)
  end

  def edit
    @unlocked_bookmarks = current_user.unlocked_bookmarks.order(unlock_date: 'DESC').page(params[:unlocked_page]).per(10)
    @locked_bookmarks = current_user.locked_bookmarks.order(created_at: 'DESC').page(params[:locked_page]).per(10)
  end

  private

  def correct_user
    user = User.find(params[:id])
    redirect_to root_path unless user == current_user
  end
end

app/views/users/_bookmark_edit_card.html.erb
<div class="col s12" id=<%= "bookmark-edit-card-#{bookmark.id}" %>>
  <div class="card">
    <div class="card-content">
      <span class="card-title blue-text"><%= bookmark.achievement.title %></span>
      <% bookmark.achievement.tags.each do |tag| %>
        <%= link_to "##{tag.name}", tag_path(tag), class: "chip" %>
      <% end %>
    </div>
    <div class="card-action">
      <%= link_to '解除取消', user_bookmark_path(current_user, bookmark), method: :patch, remote: true, class: "btn orange" if bookmark.unlocked? %>
      <%= link_to 'ストック取消', user_bookmark_path(current_user, bookmark), method: :delete, remote: true, class: "btn red" %>
    </div>
  </div>
</div>

app/views/users/_bookmarks.html.erb
<div class="row">
  <% bookmarks.each do |bookmark| %>
    <div class="col s12">
      <div class="card">
        <div class="card-content">
          <%= link_to achievement_path(bookmark.achievement) do %>
            <span class="card-title"><%= bookmark.achievement.title %></span>
          <% end %>
          <% bookmark.achievement.tags.each do |tag| %>
            <%= link_to "##{tag.name}", tag_path(tag), class: "chip" %>
          <% end %>
          <blockquote class="grey-text"><%= "実績解除日: #{l(bookmark.unlock_date)}" if bookmark.unlock_date %></blockquote>
        </div>
        <% if bookmark.user == current_user && bookmark.locked? %>
          <div class="card-action">
            <a class="btn" onclick=<%= "$('#unlockModal-#{bookmark.id}').modal('open');" %>><i class="material-icons left">lock_open</i>実績を解除</a>
            <div id="unlockModal-<%= bookmark.id %>" class="modal">
              <%= form_with(model: bookmark, url: user_bookmark_path(current_user, bookmark), method: :patch) do |form| %>
                <div class="modal-content">
                  <h4><%= bookmark.achievement.title %></h4>
                  <div id="modal-body-<%= bookmark.id %>">
                    <%= form.label :unlock_date %>
                    <%= form.text_field :unlock_date, class: "datepicker", value: l(Time.zone.now.to_date) %>
                  </div>
                </div>
                <div class="modal-footer" id="modal-footer-<%= bookmark.id %>">
                    <%= form.submit '解除', class: "btn" %>
                </div>
              <% end %>
            </div>
          </div>
        <% elsif current_user && bookmark.user != current_user %>
          <div class="card-action" id=<%= "card-action-#{bookmark.achievement.id}" %>>
            <%= render 'card_action', { bookmark: bookmark } %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<%= paginate bookmarks, remote: true, param_name: "#{status}_page" %>

app/views/users/_bookmarks_edit.html.erb
<div class="row" <%= "id=edit-locked-bookmarks" if status == 'locked'  %>>
  <% bookmarks.each do |bookmark| %>
    <%= render 'bookmark_edit_card', { bookmark: bookmark } %>
  <% end %>
</div>
<%= paginate bookmarks, remote: true, param_name: "#{status}_page" %>

app/views/users/_card_action.html.erb
<% if bookmark.achievement.users.include?(current_user) %>
  <span class="grey-text text-darken-1 valign-wrapper"><i class="material-icons">folder_special</i>ストック済</span>
<% else %>
  <%= link_to user_bookmarks_path(current_user, params: { bookmark: { achievement_id: bookmark.achievement.id } }), method: :post, remote: true, class: "valign-wrapper" do %>
    <i class="material-icons">folder</i>ストックする
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="fixed-action-btn">
  <a class="btn-floating btn-large grey" href="<%= user_path(current_user) %>">
    <i class="large material-icons">arrow_back</i>
  </a>
</div>
<br>
<div class="row valign-wrapper">
  <%= image_tag current_user.image_url, class: "circle responsive-img" %>
  <h4 class="black-text"><%= current_user.nickname %> さんの実績</h4>
</div>

<div class="row">
  <div class="col s12">
    <ul class="tabs">
      <li class="tab col s3"><a href="#unlocked">解除済</a></li>
      <li class="tab col s3"><a href="#locked">未解除</a></li>
    </ul>
  </div>
  <div id="unlocked" class="col s12">
    <%= render 'bookmarks_edit', { bookmarks: @unlocked_bookmarks, status: 'unlocked' } %>
  </div>
  <div id="locked" class="col s12">
    <%= render 'bookmarks_edit', { bookmarks: @locked_bookmarks, status: 'locked' } %>
  </div>
</div>

app/views/users/edit.js.erb
$("#unlocked").html('<%= j(render "bookmarks_edit", { bookmarks: @unlocked_bookmarks, status: 'unlocked' }) %>')
$("#locked").html('<%= j(render "bookmarks_edit", { bookmarks: @locked_bookmarks, status: 'locked' }) %>')

app/views/users/show.html.erb
<% if @user == current_user %>
  <div class="fixed-action-btn">
    <a class="btn-floating btn-large red" href="<%= edit_user_path(current_user) %>">
      <i class="large material-icons">settings</i>
    </a>
  </div>
<% end %>
<br>
<div class="row valign-wrapper">
  <%= image_tag @user.image_url, class: "circle responsive-img" %>
  <h4 class="black-text"><%= @user.nickname %>の実績</h4>
</div>
<div class="row">
  <% if @user == current_user %>
    <div class="col s12 col m5 col l3">
      <%= link_to '新しい実績を作る', new_achievement_path, class: "red lighten-2 btn btn-block" %>
    </div>
    <br>
    <br>
  <% end %>
  <div class="col s12">
    <ul class="tabs">
      <li class="tab col s3"><a href="#unlocked">解除済</a></li>
      <li class="tab col s3"><a href="#locked">未解除</a></li>
    </ul>
  </div>
  <div id="unlocked" class="col s12">
    <%= render 'bookmarks', { bookmarks: @unlocked_bookmarks, status: 'unlocked' } %>
  </div>
  <div id="locked" class="col s12">
    <%= render 'bookmarks', { bookmarks: @locked_bookmarks, status: 'locked' } %>
  </div>
</div>

app/views/users/show.js.erb
$("#unlocked").html('<%= j(render "bookmarks", { bookmarks: @unlocked_bookmarks, status: 'unlocked' }) %>')
$("#locked").html('<%= j(render "bookmarks", { bookmarks: @locked_bookmarks, status: 'locked' }) %>')
$(document).ready(function(){
  $('.datepicker').datepicker({
    container: 'body',
    format: 'yyyy/mm/dd',
    showMonthAfterYear: true,
    i18n: {
      cancel: 'キャンセル',
      done: '決定',
      months: ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
      monthsShort: ["1 /", "2 /", "3 /", "4 /", "5 /", "6 /", "7 /", "8 /", "9 /", "10 /", "11 /", "12 /"],
      weekdays: ['日', '月', '火', '水', '木', '金', '土'],
      weekdaysShort: ['日', '月', '火', '水', '木', '金', '土'],
      weekdaysAbbrev: ['日', '月', '火', '水', '木', '金', '土']
    }
  });
  $('.modal').modal({
    onCloseEnd: function() {
      if (document.getElementById('unlock-sign') != null) {
        window.location.reload();
      }
    }
  });
});