config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'achievements#index'
  resources :users, only: %i[show edit] do
    resources :bookmarks, only: %i[create show update destroy]
  end
  resources :achievements, only: %i[index show new create]
  resources :tags, only: %i[index show]
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get 'images/ogp.png', to: 'images#ogp', as: 'images_ogp'
  get 'search', to: 'achievements#search'
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :users, through: :bookmarks
  accepts_nested_attributes_for :bookmarks
  acts_as_taggable

  validates :title, presence: true, length: { maximum: 100 }, uniqueness: true
  validates_size_of :tag_list, maximum: 5

  def unlocked_users
    bookmarks.unlocked.map(&:user)
  end
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  before_action :login_required, only: %i[new create]

  def index
    @achievements = Achievement.includes(:users).order(created_at: 'DESC').page(params[:page]).per(10)
  end

  def show
    @achievement = Achievement.includes(:users).find(params[:id])
    @users = @achievement.unlocked_users.sort { |a, b| b.bookmarks.count <=> a.bookmarks.count }[0..9]
  end

  def new
    @achievement = Achievement.new
    @titles_json = Achievement.all.map { |achievement| [achievement.title, nil] }.to_h.to_json
    @chips_json = ActsAsTaggableOn::Tag.all.map { |chip| [chip.name, nil] }.to_h.to_json
  end

  def create
    @achievement = Achievement.find_by(title: achievement_params[:title]) || Achievement.new(achievement_params)

    if @achievement.save
      create_bookmark
    else
      render :new
    end
  end

  def search
    achievements_title_hit = Achievement.ransack(title_matches_any: search_words).result
    achievements_tag_hit = Achievement.tagged_with(params[:search].split, any: true, wild: true)
    @achievements = Kaminari.paginate_array(achievements_title_hit.to_a.concat(achievements_tag_hit.to_a)).page(params[:page]).per(10)
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def achievement_params
    params.require(:achievement).permit(:title, :tag_list)
  end

  def create_bookmark
    bookmark = Bookmark.new(bookmark_params)
    if bookmark.save
      redirect_to params[:only_create] ? user_path(current_user) : user_bookmark_path(current_user, bookmark)
    else
      render :new
    end
  end

  def bookmark_params
    {
      user_id: current_user.id,
      achievement_id: @achievement.id,
      unlock_date: Time.zone.now.to_date,
      status: params[:only_create] ? :locked : :unlocked
    }
  end

  def search_words
    params[:search]&.split&.map { |word| "%#{word}%" }
  end
end

app/views/achievements/_achievement_card.html.erb
<div class="card-content">
  <%= link_to achievement_path(achievement) do %>
    <span class="card-title"><%= achievement.title %></span>
  <% end %>
  <% achievement.tags.each do |tag| %>
    <%= link_to "##{tag.name}", tag_path(tag), class: "chip" %>
  <% end %>
</div>
<% if current_user %>
  <div class="card-action">
    <% if achievement.users.include?(current_user) %>
      <span class="grey-text text-darken-1 valign-wrapper"><i class="material-icons">folder_special</i>ストック済</span>
    <% else %>
      <%= link_to user_bookmarks_path(current_user, params: { bookmark: { achievement_id: achievement.id } }), method: :post, remote: true, class: "valign-wrapper" do %>
        <i class="material-icons">folder</i>ストックする
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/achievements/_achievements.html.erb
<% achievements.each do |achievement| %>
  <div class="col s12">
    <div class="card" id=<%= "achievement-card-#{achievement.id}" %>>
      <%= render 'achievement_card', { achievement: achievement } %>
    </div>
  </div>
<% end %>
<%= paginate achievements, remote: true %>

app/views/achievements/index.html.erb
<% if current_user %>
  <div class="fixed-action-btn">
    <a class="btn-floating btn-large red" href="<%= new_achievement_path  %>">
      <i class="large material-icons">mode_edit</i>
    </a>
  </div>
<% end %>

<h4 class="header center-align">みんなの実績</h4>
<div class="row">
  <div class="col s12">
    <p>目標を達成したとき、初めての体験をしたとき、人生のイベントを経験したとき… 実績を解除してシェアしよう！</p>
  </div>
</div>

<div class="row">
  <div class="col s12 col m5 col l4 col xl3">
    <% if current_user %>
      <%= link_to 'マイページへ', user_path(current_user), class: "btn btn-block" %>
    <% else %>
      <%= link_to 'Twitter でログイン', '/auth/twitter', class: "btn light-blue accent-3 btn-block" %>
  <% end %>
  </div>
</div>

<div class="row">
  <%= form_with url: search_path, method: :get do |form| %>
    <div class="col s12">
    <div class="row">
      <div class="input-field col s10">
      <i class="material-icons prefix">search</i>
        <%= form.label :search, '実績を検索' %>
        <%= form.text_field :search, autocomplete: "off" %>
      </div>
      <div class="input-field col s2">
      <%= form.submit '検索', class: "btn" %>
      </div>
      </div>
    </div>
  <% end %>
  <div id="achievements">
    <%= render 'achievements', { achievements: @achievements } %>
  </div>
</div>

app/views/achievements/index.js.erb
$("#achievements").html('<%= j(render "achievements", { achievements: @achievements }) %>')

app/views/achievements/new.html.erb
<h4 class="header center-align">新しい実績</h4>
<%= form_with(model: @achievement, url: achievements_path, method: :post, local: true) do |form| %>
  <div class="row">
    <div class="col-12">
      <div class="input-field">
        <%= form.label :title %>
        <%= form.text_field :title, autocomplete: "off", class: "autocomplete" %>
      </div>
      <br>
      <label>タグ</label>
      <div class="chips chips-autocomplete">
      </div>
      <%= form.hidden_field :tag_list %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-5">
      <div class="actions">
        <%= form.submit '作成 & 実績解除', class: "btn" %>
        <%= form.submit '作成のみ', class: "btn cyan", name: "only_create" %>
      </div>
    </div>
  </div>
<% end %>

<script>
  $('input.autocomplete').autocomplete({
    data: <%= raw @titles_json %>
  });
</script>
<script>
  $('.chips-autocomplete').chips({
    autocompleteOptions: {
      data:  <%= raw @chips_json %>
    },
    placeholder: '5つまで',
    limit: 5,
    onChipAdd: function() {
      data = M.Chips.getInstance($('.chips')).chipsData;
      document.getElementById('achievement_tag_list').value = data.map(x => x.tag);
    },
    onChipDelete: function() {
      data = M.Chips.getInstance($('.chips')).chipsData;
      document.getElementById('achievement_tag_list').value = data.map(x => x.tag);
    }
  });
</script>

app/views/achievements/search.js.erb
$("#achievements").html('<%= j(render "achievements", { achievements: @achievements }) %>')

app/views/achievements/show.html.erb
<br>
<div class="row">
  <div class="col s12">
    <div class="card" id=<%= "achievement-card-#{@achievement.id}" %>>
      <%= render 'achievement_card', { achievement: @achievement } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col s12">
    <h4 class="header center-align">実績解除した人</h4>
    <% @users.each do |user| %>
      <div class="card">
        <div class="card-content">
          <div class="row valign-wrapper">
            <%= image_tag user.image_url, class: "circle responsive-img" %>
            <%= link_to user_path(user) do %>
              <span class="card-title valign-wrapper">
                <%= user.nickname %>
              </span>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <% if @users.empty? %>
      <p class="center-align">まだだれもいないようです...<p>
    <% end %>
  </div>
</div>